/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Title
         * @description list all available title (previous period && not yet taken)
         */
        get: operations["get-api-title"];
        put?: never;
        /**
         * Register Title
         * @description Register title for next year
         */
        post: operations["post-api-title"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change Title
         * @description change title
         */
        patch: operations["patch-api-title"];
        trace?: never;
    };
    "/api/title/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail Title By Id
         * @description full data from title id
         */
        get: operations["get-api-title-id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/title/{id}/take": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take Title
         * @description take the title
         */
        post: operations["post-api-title-id-take"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Submission
         * @description list title submission
         */
        get: operations["get-api-submission"];
        put?: never;
        post?: never;
        /** Remove submission */
        delete: operations["del-api-admin-submission"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submission/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail Submission
         * @description full data from submission id
         */
        get: operations["get-api-submission-id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submission/response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Response Submission
         * @description response a submission
         */
        post: operations["post-api-submission-response"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Team
         * @description get current team detail
         */
        get: operations["get-api-team"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail Team By Id
         * @description get current team detail
         */
        get: operations["get-api-team"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team/kick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kick Member
         * @description kick member
         */
        post: operations["post-api-team-kick"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join Team
         * @description join team with id
         */
        post: operations["post-api-team-join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Profile
         * @description get current profile data
         */
        get: operations["get-api-profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change profile
         * @description change profile data
         */
        patch: operations["patch-api-profile"];
        trace?: never;
    };
    "/api/profile/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail Profile By Id
         * @description get profile data by id
         */
        get: operations["api-profile-id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all profile
         * @description get all profile
         */
        get: operations["get-api-admin-profiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/profile/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail Profile By Id
         * @description get profile data by id
         */
        get: operations["get-api-admin-profile-id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all team
         * @description get all team
         */
        get: operations["get-api-admin-teams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/team/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail Team By Id
         * @description get current team detail
         */
        get: operations["get-api-admin-team-id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/titles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Title
         * @description list all available title (previous period && not yet taken)
         */
        get: operations["get-api-admin-title"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/title/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail Title By Id
         * @description full data from title id
         */
        get: operations["get-api-admin-title-id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate New Batch
         * @description generate new capstone batch
         */
        post: operations["post-api-admin-batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove teams */
        delete: operations["del-api-admin-team"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove profile */
        delete: operations["del-api-admin-profile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove submission */
        delete: operations["del-api-admin-submission"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "data-team": {
            id: string;
            leader_id: string;
            member: components["schemas"]["data-profile-short"][];
            title_id: string;
        };
        "data-team-short": {
            id: string;
        };
        "data-profile": {
            id: string;
            cv_url: string;
            team_id: string;
            name: string;
            email: string;
        };
        "data-profile-short": {
            id: string;
            name: string;
        };
        "data-submission": {
            id: string;
            team_id: string;
            grand_design_url: string;
            team_target_id: string;
        };
        "data-submission-short": {
            id?: string;
            team_id?: string;
            team_target_id?: string;
        };
        "data-title": {
            id: string;
            title: string;
            desc: string;
            description: string;
            photo_url: string;
            proposal_url: string;
        };
        DefaultErrors: {
            /** @enum {integer} */
            status: 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 421 | 422 | 423 | 424 | 425 | 426 | 428 | 429 | 431 | 451 | 500 | 501 | 502 | 503 | 504 | 505 | 506 | 507 | 508 | 509 | 510 | 511;
            error: string;
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-api-title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example [
                     *       {
                     *         "id": "123",
                     *         "title": "makan siang bergizi",
                     *         "desc": "projek mencari sumber makan siang",
                     *         "photo_url": "http://google.com"
                     *       }
                     *     ] */
                    "application/json": {
                        id?: string;
                        title?: string;
                        desc?: string;
                        photo_url?: string;
                    }[];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "post-api-title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @example
                     */
                    photo_file?: string;
                    /**
                     * Format: binary
                     * @example
                     */
                    proposal_file?: string;
                    /** @example  */
                    title?: string;
                    /** @example  */
                    desc?: string;
                    /** @example  */
                    description?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["data-title"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "patch-api-title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @example
                     */
                    photo_file?: string;
                    /**
                     * Format: binary
                     * @example
                     */
                    proposal_file?: string;
                    /** @example  */
                    title?: string;
                    /** @example  */
                    desc?: string;
                    /** @example  */
                    description?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["data-title"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "get-api-title-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "123",
                     *       "title": "makan siang bergizi",
                     *       "desc": "projek mencari sumber makan siang",
                     *       "description": "projek panjaaang",
                     *       "photo_url": "http://google.com",
                     *       "team_id": "123221"
                     *     } */
                    "application/json": components["schemas"]["data-title"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "post-api-title-id-take": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @example
                     */
                    grand_design: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "123",
                     *       "grand_design_url": "https://average-skeleton.net/"
                     *     } */
                    "application/json": {
                        id: string;
                        grand_design_url: string;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "get-api-submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example [
                     *       {
                     *         "id": "123",
                     *         "team_id": "123"
                     *       }
                     *     ] */
                    "application/json": components["schemas"]["data-submission-short"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "del-api-admin-submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                /** @example {
                 *       "id": "123"
                 *     } */
                "application/json": {
                    id: string;
                };
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "get-api-submission-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "123",
                     *       "team_id": "1232",
                     *       "grand_design_url": "http://google.com"
                     *     } */
                    "application/json": components["schemas"]["data-submission"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "post-api-submission-response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                /** @example {
                 *       "id": "123",
                 *       "accept": false
                 *     } */
                "application/json": {
                    id: string;
                    accept: boolean;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "123",
                     *       "accept": false
                     *     } */
                    "application/json": {
                        id: string;
                        accept: boolean;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "get-api-team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "123",
                     *       "photo_url": "http://google.com",
                     *       "proposal_url": "http://google.com",
                     *       "proposal_title": "MBG",
                     *       "desc": "MBG singkat",
                     *       "description": "MBG panjang",
                     *       "leader_id": "123",
                     *       "member": [
                     *         {
                     *           "name": "member 1",
                     *           "id": "123"
                     *         }
                     *       ]
                     *     } */
                    "application/json": components["schemas"]["data-team"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "get-api-team": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "123",
                     *       "photo_url": "http://google.com",
                     *       "proposal_url": "http://google.com",
                     *       "proposal_title": "MBG",
                     *       "desc": "MBG singkat",
                     *       "description": "MBG panjang",
                     *       "leader_id": "123",
                     *       "member": [
                     *         {
                     *           "name": "member 1",
                     *           "id": "123"
                     *         }
                     *       ]
                     *     } */
                    "application/json": components["schemas"]["data-team"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "post-api-team-kick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                /** @example {
                 *       "id": "123"
                 *     } */
                "application/json": {
                    id: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "123"
                     *     } */
                    "application/json": {
                        id: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "post-api-team-join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                /** @example {
                 *       "id": "123"
                 *     } */
                "application/json": {
                    id: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "123"
                     *     } */
                    "application/json": {
                        id: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "get-api-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "123",
                     *       "cv_url": "http://google.com",
                     *       "team_id": "123",
                     *       "name": "name",
                     *       "email": "email@email.com"
                     *     } */
                    "application/json": components["schemas"]["data-profile"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "patch-api-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** @example  */
                    name?: string;
                    /**
                     * Format: email
                     * @example
                     */
                    email?: string;
                    /**
                     * Format: binary
                     * @example
                     */
                    cv_file?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["data-profile"];
                };
            };
        };
    };
    "api-profile-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["data-profile"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "get-api-admin-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example [
                     *       {
                     *         "id": "123",
                     *         "name": "123"
                     *       }
                     *     ] */
                    "application/json": {
                        id?: string;
                        name?: string;
                    }[];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "get-api-admin-profile-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["data-profile"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "get-api-admin-teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["data-team-short"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {integer} */
                        status: 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 421 | 422 | 423 | 424 | 425 | 426 | 428 | 429 | 431 | 451 | 500 | 501 | 502 | 503 | 504 | 505 | 506 | 507 | 508 | 509 | 510 | 511;
                        error: string;
                        message: string;
                    };
                };
            };
        };
    };
    "get-api-admin-team-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "123",
                     *       "photo_url": "http://google.com",
                     *       "proposal_url": "http://google.com",
                     *       "proposal_title": "MBG",
                     *       "desc": "MBG singkat",
                     *       "description": "MBG panjang",
                     *       "leader_id": "123",
                     *       "member": [
                     *         {
                     *           "name": "member 1",
                     *           "id": "123"
                     *         }
                     *       ]
                     *     } */
                    "application/json": components["schemas"]["data-team"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "get-api-admin-title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example [
                     *       {
                     *         "id": "123",
                     *         "title": "makan siang bergizi",
                     *         "desc": "projek mencari sumber makan siang",
                     *         "photo_url": "http://google.com"
                     *       }
                     *     ] */
                    "application/json": {
                        id?: string;
                        title?: string;
                        desc?: string;
                        photo_url?: string;
                    }[];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "get-api-admin-title-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "123",
                     *       "title": "makan siang bergizi",
                     *       "desc": "projek mencari sumber makan siang",
                     *       "description": "projek panjaaang",
                     *       "photo_url": "http://google.com",
                     *       "team_id": "123221"
                     *     } */
                    "application/json": components["schemas"]["data-title"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "post-api-admin-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                /** @example {
                 *       "year": "2024"
                 *     } */
                "application/json": {
                    year: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example [
                     *       {
                     *         "id": "123",
                     *         "code": "aaa"
                     *       }
                     *     ] */
                    "application/json": {
                        id?: string;
                        code?: string;
                    }[];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "del-api-admin-team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                /** @example {
                 *       "id": "123"
                 *     } */
                "application/json": {
                    id: string;
                };
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "del-api-admin-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                /** @example {
                 *       "id": "123"
                 *     } */
                "application/json": {
                    id: string;
                };
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
    "del-api-admin-submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                /** @example {
                 *       "id": "123"
                 *     } */
                "application/json": {
                    id: string;
                };
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultErrors"];
                };
            };
        };
    };
}
